### ISSUE TITLE
Cannot compress file that larger than 2GB

### ISSUE THREAD

**Issue by kiddliu** [dzek69/brotli-cli#19]
It seems that the file about to compress is loaded with API `readFile` which limits by the Node.js buffer

**Comment by dzek69** [comment]
Hello, thanks for your report, this has been fixed... at least partially.

Because the zlib module expects the Buffer (or equivalent data format) and can't work with streams - files must be all loaded into memory. I was able to avoid `readFile` on too big files and bump the max file size to 4GB (on modern systems), but this is a hard limit I can't currently work around.

I added some warnings into README to address than.

I hope this helps with your use case :)

**Comment by kiddliu** [comment]
That's OK...now I workaround this with GNU split, feeding each part to the tool.
