### ISSUE TITLE
Support globbing

### ISSUE THREAD

**Issue by rektide** [dzek69/brotli-cli#2]
> support globbing (currently *.{js,css} doesn't work)

Via https://github.com/foliojs/brotli.js/issues/5#issuecomment-439413685

**Comment by dzek69** [comment]
Hello, thanks for your suggestion.

I wrote this library within a minutes, because I needed simple CLI tool. I always wanted to update it (like many many other things) but never had a time for it.

So I finally spent some hours and released new version :)

Please install newest version and run `brotli-cli help` for usage examples with glob support.
